spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/book_lending?serverTimezone=UTC&useUnicode=true&characterEnconding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.hyb.entity
  mapper-locations: classpath:com/hyb/mapper/*.xml

pagehelper:
  #指定数据库，不指定的话会默认自动检测数据库类型
  helper-dialect: mysql
  #是否启用分页合理化。如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；不启用的，以上两种情况都会返回空数据
  reasonable: true
  #默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  #为了支持startPage(Object params)方法
  params: countSql

logging:
  level:
    # 控制台打印sql
    com.hyb.mapper: debug

