spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/book_lending?serverTimezone=UTC&useUnicode=true&characterEnconding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.hyb.entity
  mapper-locations: classpath:com/hyb/mapper/*.xml
pagehelper:
  helper-dialect: mysql  #指定数据库，不指定的话会默认自动检测数据库类型
  reasonable: true  #是否启用分页合理化。如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；不启用的，以上两种情况都会返回空数据
  support-methods-arguments: true #默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: countSql  #为了支持startPage(Object params)方法
logging:
  level:
    com.hyb.mapper: debug  # 控制台打印sql
wx:
  login:
    app-id: 我是qpt的爹
    secret: 我是qpt的爹
ocr:
  APP_ID: "25750682"
  API_KEY: "TPEbBaMi35VAbal27KYHqnGQ"
  SECRET_KEY: "3CHDc29B9QkMhDMfibwogdaaPfcyvv6f"